# This is a basic workflow to help you get started with Actions

name: Kindle 笔记强制更新 channel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  # schedule:
    # 使用 Cron 表达式定义时间
    # - cron: '0/30 * * * *' # 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r script/note_forward/requirements.txt --upgrade

      - name: Run the kindle note forward script
        run: |
          export MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }}
          export ICLOUD_EMAIL=${{ secrets.ICLOUD_EMAIL }}
          export ICLOUD_APP_PASSWORD=${{ secrets.ICLOUD_APP_PASSWORD }}
          export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          export REPORT_CHANNEL=${{ secrets.REPORT_CHANNEL }}
          export NEODB_TOKEN=${{ secrets.NEODB_TOKEN }}
          export BANGUMI_TOKEN=${{ secrets.BANGUMI_TOKEN }}
          export COS_SECRET_ID=${{ secrets.COS_SECRET_ID }}
          export COS_SECRET_KEY=${{ secrets.COS_SECRET_KEY }}
          export IMAGE_COS_BUCKET=${{ secrets.IMAGE_COS_BUCKET }}
          export PUSH_TAG_INFO_TO_MONGODB="true"
          python3 script/note_forward/index.py --push_channel --force_update
