# This is a basic workflow to help you get started with Actions

name: Kindle 笔记导出

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r script/kindle_note_forward/requirements.txt

      - name: Run the kindle note forward script
        run: python script/kindle_note_forward/index.py --atlas_uri=${{ secrets.ATLAS_URI }} --push_github --push_atlas --html_path=kindle_note/origin --markdown_path=docs/KindleNotes

      - name: Run safe dir
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Push formatted markdown doc
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.G_T }}
          branch: master
          message: '📝 docs: 上传 kindle 导出笔记'
          force: true
